ipAddress=127.0.0.1
port=4723
browser=chrome
AndroidDeviceNames=RahulPhone
nodeBinPath=/usr/local/Cellar/node/20.8.0/bin
appiumMainJsPath=/usr/local/Cellar/node/20.8.0/lib/node_modules/appium/build/lib/main.js
chromedriverPath=/usr/local/bin/chromedriver
